#!/usr/bin/env python3
"""
Run Chimera on real research task with MiniMax API.
Sets up real API calls and generates comprehensive research report.
"""

import os
import sys
import json
from datetime import datetime

# Set up environment for MiniMax
os.environ["MINIMAX_API_KEY"] = "sk-cp-Rg64VbM5FkwJrZkiTYazH3PXihEFIaY4ohU5r-zg-aAyPN60puG0IaWTQ9AJXdbGpzTlqcozbsIEhpquqkg3GA9qTeN-C_SXTJsOSYWQhPuFhIPPuULgs1I"
os.environ["MINIMAX_BASE_URL"] = "https://api.minimax.io/anthropic"

# Add chimera to path
sys.path.insert(0, "/Users/jleechan/Downloads/chimera")

from chimera.orchestrator import SwarmOrchestrator
from chimera.utils import load_llm_client

RESEARCH_QUERY = """
What are the most promising approaches to achieving nuclear fusion energy in 2026?
Include technical challenges, timelines, and key players.
"""

OUTPUT_FILE = "/Users/jleechan/Downloads/chimera/research_report_fusion_2026.md"

def run_chimera_research():
    """Run the full Chimera 22-agent pipeline on fusion energy research."""

    print("="*60)
    print("CHIMERA REAL API RESEARCH")
    print("="*60)
    print(f"Query: {RESEARCH_QUERY.strip()}")
    print()

    # Load real LLM client
    client = load_llm_client()
    if client is None:
        print("[ERROR] Failed to load MiniMax API client")
        return None

    print("[OK] MiniMax client loaded successfully")

    # Initialize orchestrator in FIXED mode with real API
    orch = SwarmOrchestrator(use_gnn=False, mock_mode=False)

    # Inject the real client into all agents
    for agent in orch.agents.values():
        agent.set_llm_client(client)

    print("[OK] All 22 agents initialized with MiniMax client")
    print()

    # Run the fixed pipeline
    print("[START] Running 22-agent fixed pipeline...")
    result = orch.run_research(RESEARCH_QUERY.strip(), mode="fixed")

    return result

def generate_report(result: dict) -> str:
    """Generate formatted markdown research report."""

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    report = f"""# Nuclear Fusion Energy Research Report
## Chimera Multi-Agent Research | April 2026

**Generated:** {timestamp}
**Pipeline Mode:** Fixed 22-Agent
**Quality Score:** {result.get('quality_gate', {}).get('score', 'N/A')}/10
**Token Estimate:** {result.get('total_tokens_estimate', 'N/A'):,}

---

## Executive Summary

{result.get('report', 'No synthesis generated')[:2000]}

---

## Detailed Findings

### Literature Synthesis

The Chimera swarm deployed 5 literature miners and 3 domain experts to compile
comprehensive findings on nuclear fusion approaches.

### Technical Approaches

{_extract_section(result.get('report', ''), 'Technical Approaches')}

### Key Challenges

{_extract_section(result.get('report', ''), 'Challenges')}

### Timeline Projections

{_extract_section(result.get('report', ''), 'Timeline')}

### Key Players

{_extract_section(result.get('report', ''), 'Players')}

---

## Quality Gate Evaluation

- **Approved:** {result.get('quality_gate', {}).get('approved', 'N/A')}
- **Score:** {result.get('quality_gate', {}).get('score', 'N/A')}/10
- **Issues Found:** {result.get('quality_gate', {}).get('issues', 'None identified')}

---

## Swarm Performance Analysis

**Meta-Evolution Insights:**
{result.get('meta_evolution', 'No analysis available')}

---

## Methodology

This report was generated using Project Chimera's 22-agent multi-agent swarm:

1. **Router Agent** - Decomposed query into research sub-tasks
2. **5 Literature Miners** - Parallel web search and paper analysis
3. **3 Domain Experts** - Technical deep-dives on fusion approaches
4. **4 Critics** - Identified weaknesses and gaps in findings
5. **Fact Checker** - Verified claims against sources
6. **Synthesizer** - Integrated all findings into coherent report
7. **Quality Gate** - Evaluated report completeness and accuracy
8. **Explainer** - Generated accessible explanations
9. **Meta-Evolver** - Analyzed swarm performance
10. **Knowledge Keeper** - Stored key findings for future reference

---

*Report generated by Project Chimera | Neural Network of LLM Agents*
"""
    return report

def _extract_section(text: str, section_name: str) -> str:
    """Extract a section from text by looking for headers."""
    lines = text.split('\n')
    in_section = False
    section_lines = []

    for line in lines:
        if line.startswith('##') and section_name.lower() in line.lower():
            in_section = True
            continue
        elif line.startswith('##') and in_section:
            break
        if in_section:
            section_lines.append(line)

    result = '\n'.join(section_lines).strip()
    return result if result else f"[{section_name} content not separately identified in synthesis]"

if __name__ == "__main__":
    print("[CLI_START] Running Chimera with MiniMax API...")

    result = run_chimera_research()

    if result:
        print("\n[OK] Pipeline complete. Generating report...")

        # Generate and save report
        report = generate_report(result)
        with open(OUTPUT_FILE, 'w') as f:
            f.write(report)

        print(f"[CLI_RESULT] Report written to {OUTPUT_FILE}")
        print(f"[CLI_RESULT] Quality score: {result.get('quality_gate', {}).get('score', 'N/A')}")
        print(f"[CLI_RESULT] Token estimate: {result.get('total_tokens_estimate', 'N/A'):,}")

        # Also save raw result as JSON for debugging
        json_file = OUTPUT_FILE.replace('.md', '_raw.json')
        with open(json_file, 'w') as f:
            # Convert result to JSON-serializable format
            serializable = {}
            for k, v in result.items():
                try:
                    serializable[k] = v
                except:
                    serializable[k] = str(v)
            json.dump(serializable, f, indent=2, default=str)
        print(f"[CLI_RESULT] Raw result saved to {json_file}")
    else:
        print("[ERROR] Pipeline failed")
        sys.exit(1)
